name: weather_test_app
description: Test Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  easy_localization: ^3.0.0
  adaptive_theme: ^2.3.0
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  dotted_border: ^2.0.0+2
  weather_repository:
    path: packages/weather_repository
  weather_icons: ^3.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/translations/