name: weather_repository
description: Weather Repository.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  weather_metadata_api:
    path: ../weather_metadata_api


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0