name: weather_metadata_api
description: API client for Weather.
version: 0.0.1

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  http:

dev_dependencies:
  flutter_lints: ^1.0.0